[package]
name = "color-utf8-code"
version = "1.0.0"
edition = "2024"

[dependencies]
bytes = "1.10.1"
clap = { version = "4.5.39", features = ["derive"] }
image = "0.25.6"
reqwest = "0.12.19"
tokio = { version = "1.45.1", features = ["macros", "rt"] }
